language: java
sudo: false # faster builds
before_install:
- chmod +x mvnw
script:
# - "./mvnw clean install -B"
- "./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar"
after_success:
- bash <(curl -s https://codecov.io/bash)
addons:
sonarcloud:
  organization: mohanapriya
  token:
    secure: 40b88f9e151489c63029161c7ccbaa042c82e94a