language: java
sudo: false # faster builds
before_install:
- chmod +x mvnw
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
provider: heroku
api_key: cae731da-6123-4e73-a583-374d1ae3b8ad
app: travis1
addons:
sonarcloud:
  organization: mohanapriya
  token:
    secure: 6b36f216945887c5585ad8e36ff225e37dd76757